= rmoff's Blog (source)

image::https://github.com/rmoff/rmoff-blog/workflows/GitHub%20Pages/badge.svg?branch=master[]

This is the source for https://rmoff.net, built using Hugo and hosted via GitHub pages.

== Running locally

[source,bash]
----
docker run --rm -it \
  -v $(pwd):/src \
  -p 1313:1313 \
  klakegg/hugo:0.85.0-asciidoctor-onbuild \
  server --buildFuture --buildDrafts
----

== Creating a new post

[source,bash]
----
docker run --rm -it \
  -v $(pwd):/src \
  klakegg/hugo:0.85.0-asciidoctor-onbuild \
  new content/post/my_new_post.adoc
----

== Link checking

Run this locally to check the local state once the server is running: 

[source,bash]
----
docker run --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:0.85.0-asciidoctor-onbuild
docker run -v $PWD:/check ghcr.io/untitaker/hyperlink:0.1.26 /check/public/
----

Link checking is also configuring as an action for any PR, and as a scheduled action. 

== Broken theme

The theme used (https://github.com/xaprb/story[story]) is no longer maintained, and is broken with the latest version of Hugo (`0.96.0`). It may be broken with earlier versions too (I've not built it for a while). It does work with `0.82.1``.

[source,bash]
----
hugo v0.96.0+extended darwin/amd64 BuildDate=unknown
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
Error: Error building site: failed to render pages: render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
Built in 1800 ms
----

I found this https://discourse.gohugo.io/t/cant-evaluate-field-hugo-in-hugolib-pagestate/37862/3[relevant thread] but don't understand enough about Hugo and its themes to do anything other than hack around…so instead I'm just hard-coding my dependence back to 0.82 and leaving it there. Maybe at some point I'll try out a new theme (yak shaving when I should be doing something else ;-) )
