= rmoff's Blog (source)

image::https://github.com/rmoff/rmoff-blog/actions/workflows/gh-pages-deployment.yml/badge.svg[Build and Deploy to GitHub Pages,link=https://github.com/rmoff/rmoff-blog/actions/workflows/gh-pages-deployment.yml]

image::https://github.com/rmoff/rmoff-blog/actions/workflows/external_link_check.yml/badge.svg?branch=main&event=schedule[Check External Links,link=https://github.com/rmoff/rmoff-blog/actions/workflows/external_link_check.yml]


This is the source for https://rmoff.net, built using Hugo and hosted via GitHub pages.

== Running locally

[source,bash]
----
docker run --rm -it \
  -v $(pwd):/src \
  -p 1313:1313 \
  klakegg/hugo:0.105.0-asciidoctor-onbuild \
  server
----

== Building reveal.js presentations

This blog includes reveal.js presentations built from AsciiDoc source files. To build presentations locally, you need to install the `asciidoctor-revealjs` gem:

[source,bash]
----
gem install asciidoctor-revealjs
----

Presentations are built using the `build-slides.sh` script, which finds all `slides.adoc` files in the `content/talks` directory and converts them to HTML using `asciidoctor-revealjs`. The script is automatically run before Hugo builds in both the local deploy script and GitHub Actions workflows.

== Creating a new post

[source,bash]
----
id=my-new-article-slug \
&& git checkout main && git pull && git checkout -b $id && docker run --rm -it \
 -v $(pwd):/src \
 klakegg/hugo:0.105.0-asciidoctor-onbuild \
 new content/post/$id.adoc
----

== Link checking

Run this locally to check the state of the local copy.

[source,bash]
----
mkdir /tmp/hugo_public && \
docker run --rm -it -v $(pwd):/src -v /tmp/hugo_public:/tmp/public klakegg/hugo:0.105.0-asciidoctor-onbuild  --buildFuture --buildDrafts -d /tmp/public && \
docker run -v /tmp/hugo_public:/check ghcr.io/untitaker/hyperlink:0.1.26 /check &&
rm -rf /tmp/hugo_public
----

Link checking is also configuring as an action for any PR.

== Theme

The theme used (https://github.com/xaprb/story[story]) is no longer maintained, and needed fixing to work with versions > 0.86. When built, it threw these errors:

[source,bash]
----
hugo v0.96.0+extended darwin/amd64 BuildDate=unknown
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
ERROR 2022/04/01 11:15:15 render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
Error: Error building site: failed to render pages: render of "page" failed: "/Users/rmoff/git/rmoff-blog/themes/story/layouts/_default/baseof.html:12:10": execute of template failed: template: _default/single.html:12:10: executing "_default/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
Built in 1800 ms
----

I fixed it by https://github.com/rmoff/rmoff-blog/commit/cc235ef6f990d85995329da3fe80f62fb1d667c0#diff-67fd70a42c2bf7d56a85104f205d0e19f77f08f5335b21dbbd98ef808cd5f128[removing the `.HugoGenerator` code] and it works just fine now.
