---
draft: false
title: 'Stumbling into AI: Part 5—Agents'
date: "2025-09-17T09:12:04Z"
image: "/images/2025/09/"
thumbnail: "/images/2025/09/"
credit: "https://bsky.app/profile/rmoff.net"
categories:
- AI
- Agents
- Stumbling into AI
---

:source-highlighter: rouge
:icons: font
:rouge-css: style
:rouge-style: monokai

_A link:/categories/stumbling-into-ai[short series] of notes for myself as I learn more about the AI ecosystem as of September 2025._
_The driver for all this is understanding more about Apache Flink's https://github.com/apache/flink-agents[*Flink Agents*] project, and Confluent's https://www.confluent.io/product/streaming-agents/[**Streaming Agents**]._

I started off link:/categories/stumbling-into-ai/[this series] somewhat randomly, looking at link:/2025/09/04/stumbling-into-ai-part-1mcp/[Model Context Protocol (MCP)].
It's pretty neat, but it's a helper technology to make things easier to use and provide a richer experience.
Next I tried to wrap my head around link:/2025/09/08/stumbling-into-ai-part-2models/[Models]—mostly LLMs, but also with an link:/2025/09/08/stumbling-into-ai-part-2models/#_addendum_there_are_models_and_then_there_are_models_a_k_a_not_all_models_are_llms[addendum] discussing other types of model too.
Along the lines of MCP, link:/2025/09/12/stumbling-into-ai-part-3rag/[Retrieval Augmented Generation (RAG)] is another helper technology that on its own doesn't do anything but combined with an LLM gives it added smarts.
I took a brief moment in link:
RAG and MCP combined make for a bunch of nice capabilities beyond the LLM alone, but what I'm really circling around here is what we can when we combine all these things: *Agents*!

<!--more-->

== Agent

Let's go with https://en.wikipedia.org/wiki/Software_agent[Wikipedia's definition]:

> In computer science, a software agent is a computer program that acts for a user or another program in a relationship of agency.

We can get more specialised if we look at Wikipedia's entry for an https://en.wikipedia.org/wiki/Intelligent_agent[Intelligent Agent]:

> In artificial intelligence, an intelligent agent is an entity that perceives its environment, takes actions autonomously to achieve goals, and may improve its performance through machine learning or by acquiring knowledge.

Citing Wikipedia is perhaps the laziest ever blog author's trick, but I offer no apologies 😜.
Behind all the noise and fuss, this is what we're talking about: a bit of software that's going to go and do something for you (or your company) _autonomously_.


The AI bit comes into it when we consider what happens when we take a traditional Agent ("_Order more biscuits when there are only two left_") and add some smarts.
What about "_Order more biscuits when there are only two left, **picking the most appropriate type based on the stock and the supplier and who is in the office next week and their known preferences for jammy dodgers vs hobnobs**_".

Another canonical examples of an AI Agent might include travel booking.
Perhaps you tell it when you want to go, the kind of vacation you like, and what your budget is; it then goes and finds where it nice at that time of year, figures out travel plans within your budget, and either proposes an itinerary or even books it for you.
Another variation would be you tell it *where*, and then it integrates with your calendar to figure out the _when_.

== Multi-agent System (MAS)

Just as you can build computer systems as monoliths (everything done in one place) or microservices (multiple things, each responsible for a discrete operation or domain), you can also have one big agent trying to do everything (probably not such a good idea) or individual agents each good at their particular thing that are then hooked together into what's known as a Multi-agent System (MAS).
Sean Falconer's https://seanfalconer.medium.com/building-a-meal-planning-agent-with-apache-kafka-and-apache-flink-254bc5a8d7c5[family meal planning demo] is a good example of a MAS.
One agent plans the kids meals, one the adult's meals, another combines the two into a single plan, and so on.

=== Agentic AI

This is a fancy way of saying you're using AI through an Agent, or set of Agents (MAS).



chatbot, hard code some rules, human in the loop
