---
draft: true
title: 'Life as a Developer Advocate—seven months into a pandemic'
date: "2020-10-20T22:15:59+01:00"
image: "/images/2020/10/"
thumbnail: "/images/2020/10/"
credit: "https://twitter.com/rmoff/"
categories:
- DevRel
---

Back in March 2020 the western world came to somewhat of a juddering halt, thanks to COVID-19. No-one knew then what would happen, but there was the impression that whilst the next few months were a write-off for sure, _maybe_ things would pick up again later in the year.

It's now late October 2020, and nothing is picking up any time soon. Summer provided a respite from the high levels of infection and mortality (in the UK at least), but numbers are spiking again in many places around the world and what was punted down the river back in March is being firmly punted yet again now. 

By now, people and companies have begun seriously adapting to what a world with minimal face-to-face interactions can look like. Some of the big tech companies have made the decision to let their staff work from home indefinitely. Virtual conferences are now a thing, and maybe whilst not quite out of nappies [diapers] are certainly starting to grow up and toddle around if albeit somewhat wobbly at times. 

I wrote link:/2020/03/13/are-tech-conferences-dead/[Are Tech Conferences Dead?] back in March in which I cover a lot of the foundations of online vs in-person conferences, pros & cons - which I'm not going to regurgitate there. Instead I've been mulling over in recent weeks the impact that this has all had on the life of a Developer Advocate, specifically this one—me—and what the future could look like. 

It probably seems crass and self-indulgent to be writing this when around us people are actually dying as a result of this pandemic. This article is not meant as that, but as a reflection on life in my little niche world of DevRel despite that.

== What are your priorities?

I've link:/2019/02/09/travelling-for-work-with-kids-at-home/[written before] about the impact of working away from home, both on family life but also on link:/2019/09/19/staying-sane-on-the-road-as-a-developer-advocate/[one's own well-being]. The funny thing about *working* from *home* is that the worlds of paid employment and personal life still collide, but in different ways. Being at home 100% of the time has forced me to be brutally honest with myself in a way that I probably never was whilst on the road. It turns out that a bunch of hypotheses that I couldn't actually test before are now being tested and disproved: 

* ❌ "Travelling is just part of my job". Turns out you can do a crap-ton of Developer Advocacy from the comfort of one's own home. Part of that is circumstance; once in-person conferences resume, will I still have the same opportunities to participate remotely as I currently do?
* ❌ "The kids are used to me travelling, it's fine". Well, they were used to it, but that is not to say it was fine, _at all_. 
* ❌ "I enjoy the travel". I enjoyed visiting _places_. Getting up at 0400, sitting on a cramped plane, airport lounges…is shit. Crappy travel with my family for two weeks on the beach in the sun is worth it, and it makes up a fraction of the trip. Crappy travel for a conference or meetup accounts for a significant part of the trip, and is _all the time_. If you're fool enough to do it so often you get status on the airlines etc then…yay…you get slightly-less-crappy travel that's still crappy travel at the end of the day. 
* ✅ "You need to see people in person". This one I still hold as true. Some virtual conferences have gone quite a long way in bridging the gap, but even the very best have not really been within any distance of the real thing. 

All of this has given me plenty of pause for thought, in a "stop the world I want to get off" kind of way that the pandemic has actually given us the gift of being able to do. 

== The Sum is greater than the parts

Being on the road 30% is not the same as being at home 70%. It's like being at home maybe 50%, if that. Especially if that 30% is made up of a day here, two days there, across the twenty working days of the month, the family calendar soon starts to look like some Swiss cheese. 




----
Spoke at GOTOpia this morning, and I love how they are running the virtual conf. Instead of a gazillion speaker emails, multiple platform logons, blah blah  - they send you an iCal for your talk with a Zoom.
At your talk time, you connect to the Zoom - and then just chat with the host and attendees before segueing into the actual talk. It makes it feel so much more natural and like there's a human being there. Such a nice contrast to the confs where you're just speaking into the bottomless void of your webcam and dying a little inside.
12:06
maybe it won't scale for large confs, and maybe if it were free reg you'd get jerks spoiling it, but it's the closest I've got to an actual conf feeling out of all the talks I've done since March
----