---
title: 'First-timer tips for Oracle Open World'
date: "2014-10-08T00:00:00+00:00"
url: "/2014/10/08/first-timer-tips-for-oracle-open-world/"
draft: false
categories:
- OBIEE
- Performance
- Graph
- Data Visualisation
original_source: "rittmanmead"
original_url: "https://www.rittmanmead.com/blog/2014/10/first-timer-tips-for-oracle-open-world/"
classes:
- feature-nohdr
---

NOTE: This post originally appeared on the link:https://www.rittmanmead.com/blog/2014/10/first-timer-tips-for-oracle-open-world/[Rittman Mead blog].

Last week I had the great pleasure to attend Oracle Open World (OOW) for the first time, presenting link:http://www.slideshare.net/themoff/oow14-robin-moffatt-no-silver-bullets-obiee-performance-in-the-real-world[No Silver Bullets - OBIEE Performance in the Real World] at one of the ODTUG user group sessions on the Sunday. It was a blast, as the saying goes, but the week before OOW I was more nervous about the event itself than my presentation. Despite having been to smaller conferences before, OOW is link:https://twitter.com/oracleopenworld/status/517709375972978688[vast in its scale] and I felt like the week before going to university for the first time, full of uncertainty about what lay ahead and worrying that everyone would know everyone else except you! So during the week I jotted down a few things that I'd have found useful to know ahead of going and hopefully will help others going to OOW take it all in their stride from the very beginning.


== Coming and going


I arrived on the Friday at midday SF time, and it worked perfectly for me. I was jetlagged so walked around like a zombie for the remainder of the day. Saturday I had chance to walk around SF and get my bearings both geographically, culturally and climate. Sunday is "day zero" when all the user group sessions are held, along with the opening OOW keynote in the evening. I think if I'd arrived Saturday afternoon instead I'd have felt a bit thrust into it all straight away on the Sunday.


In terms of leaving, the last formal day is Thursday and it's full day of sessions too. I left straight after breakfast on Thursday and I felt I was leaving too early. But, OOW is a long few days & nights so chances are by Thursday you'll be beat anyway, so check the schedule and plan your escape around it.


== Accomodation


*Book in advance!*Like, at least two months in advance. There are 60,000 people descending on San Francisco, all wanting some place to stay.


Get link:https://www.airbnb.com/[airbnb], a lot more for your money than a hotel. Wifi is generally going to be a _lot_ better, and having a living space in which to exist is nicer than just a hotel room. Don't fret about the "perfect" location - anywhere walkable to link:https://www.google.co.uk/maps/place/Moscone+Center/@37.783944,-122.401289,17z/data=!3m1!4b1!4m2!3m1!1s0x8085808765f557c9:0x2f848d8f5b09f78f[Moscone] (where OOW is held) is good because it means you can drop your rucksack off at the end of the day etc, but other than that the events are spread around so you'll end up walking further to at least some of them. Or, get an link:http://uber.com/[Uber] like the locals do!


== Sessions


Go to link:http://www.oraclerealworld.com/oaktable-world/[Oak Table World] (OTW), it's great, and free. Non-marketing presentations from some of the most respected speakers in the industry. Cuts through the BS. It's also basically on the same site as the rest of OOW, so easy to switch back and forth between OOW/OTW sessions.


Go and say hi to the speakers. In general they're going to want to know that you liked it. Ask questions -- hopefully they like what they talk about so they'll love to speak some more about it. You'll get more out of a five minute chat than two hours of keynote. And on that subject, don't fret about dropping sessions -- people tweet them, the slides are usually available, and in fact you could be sat at your desk instead of OOW and have missed the whole lot so just be grateful for what you do see. Chance encounters and chats aren't available for download afterwards; most presentations are. Be strict in your selection of "must see" sessions, lest you drop one you really really did want to see.


Use the schedule builder in advance, but download it to your calendar (watch out for line-breaks in the exported file that will break the import) and sync it to your mobile phone so you can see rapidly where you need to head next. Conference mobile apps are rarely that useful and frequently bloated and/or unstable.


Don't feel you need to book every waking moment of every day to sessions. It's not slacking if you go to half as many but are twice as effective from not being worn out!


== Dress


Dress wise, jeans and polo is fine, company polo or a shirt for delivering presentations. Day wear is fine for evenings too, no need to dress up. Some people do wear shorts but they're in the great minority. There are lots of suits around, given it is a customer/sales conference too.


== Socialising


The sessions and random conversations with people during the day are only part of OOW -- the geek chat over a beer (or soda) is a big part too. Look out for the Pythian blogger meetup, meetups from your country's user groups, companies you work with, and so on.


Register for the evening events that you get invited to (ODTUG, Pythian, etc) because often if you haven't pre-registered you can't get in if you change your mind, whereas if you do register but then don't go that's fine as they'll bank on no-shows. The evening events are great for getting to chat to people (dare I say, networking), as are the other events that are organised like the swim in the bay, run across the bridge, etc.


Sign up for stuff like link:https://www.facebook.com/events/460098430793716/[swim in the bay],  it's good fun - and I can't even swim really. Run/Bike across the bridge are two other events also organised. Hang around on twitter for details, people like link:https://twitter.com/yvelik[Yury Velikanov] and link:https://twitter.com/thatjeffsmith[Jeff Smith] are usually in the know if not doing the actual organising.


== General


When the busy days and long evenings start to take their toll don't be afraid to duck out and go and decompress. Grab a shower, get a coffee, do some sight seeing. Don't forget to drink water as well as the copious quantities of coffee and soda.


Get a data package for your mobile phone in advance of going eg £5 per day unlimited data. Conference wifi is just about OK at best, often flaky. Trying to organise short-notice meetups with other people by IM/twitter/email gets frustrating if you only get online half an hour after the time they suggested to meet!


Don't pack extra clothes 'just in case'. Pack minimally because (1) you are just around the corner from Market Street with Gap, Old Navy etc so can pick up more clothes cheaply if you need to and (2) you'll get t-shirts from exhibitors, events (eg link:https://www.facebook.com/events/460098430793716/[swim in the bay]) and you'll need the suitcase space to bring them all home. Bring a suitcase with space in or that expands, don't arrive with a suitcase that's already at capacity.


== Food


So much good food and beer. Watch out for some of the American beers; they seem to start at about 5% ABV and go upwards, compared to around 3.6% ABV here in the UK. Knocking back link:https://untappd.com/b/russian-river-brewing-company-pliny-the-elder/4499[this] at the same rate as link:https://untappd.com/b/thwaites-brewery-original/25699[this] will get messy.


In terms of food you really are spoilt, some of my favourites were:


* link:http://lorisdiner.com/[Lori's diner] (link:https://www.google.com/maps/place/351+Mason+St/@37.786885,-122.409759,16z/data=!4m2!3m1!1s0x8085808f003e1acb:0x7b4b6d8295ddc1b1?hl=en-US[map]) : As a brit, I loved this American Diner, and great food - link:https://twitter.com/rmoff/status/517112893360578561[yum] link:https://twitter.com/rmoff/status/517229213251039232[yum]. 5-10 minutes walk from Moscone.
* link:http://www.melsdrive-in.com/[Mel's drive-in] (link:https://www.google.com/maps/place/Mel's+Drive-In/@37.786885,-122.409759,16z/data=!4m5!1m2!2m1!1smel's+diner!3m1!1s0x80858087ad365689:0x6ec3c96a9e0edd27?hl=en-US[map]) : Just round the corner from Moscone, very busy but lots of seats. Great american breakfast experience! link:https://twitter.com/rmoff/status/517727648261611520[yum]
* link:http://www.thegrovesf.com/[Grove] (link:https://www.google.com/maps/place/Grove+Yerba+Buena/@37.786547,-122.401976,17z/data=!3m1!4b1!4m2!3m1!1s0x80858087ec8d9c89:0x74ef87a11bfe299c?hl=en-US[map]) : Good place for breakfast if you want somewhere a bit less greasy than a diner (WAT!)

NOTE: This post originally appeared on the link:https://www.rittmanmead.com/blog/2014/10/first-timer-tips-for-oracle-open-world/[Rittman Mead blog].
