---
draft: true
title: 'Fixing gem errors in Hugo'
date: "2021-09-07T10:05:43+01:00"
credit: "https://twitter.com/rmoff/"
categories:
- Hugo
---

:source-highlighter: rouge
:icons: font
:rouge-css: style
:rouge-style: github

After some changes on my Mac (maybe OS upgrade - not sure) my local install of Hugo stopped working. Recording the errors and steps I took (random jiggling to unbreak things) to help others in case it helps. 

<!--more-->

The repeated errors I got were: 

[source]
----
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.10.0 because its extensions are not built. Try: gem pristine ffi --version 1.10.0
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring posix-spawn-0.3.15 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.15
Ignoring posix-spawn-0.3.13 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.13
Ignoring ruby-debug-ide-0.6.0 because its extensions are not built. Try: gem pristine ruby-debug-ide --version 0.6.0
----

## Fix

NOTE: I am not a Ruby guy and don't have a clue what these errors actually mean! If there is a better or more accurate way to fix them please do https://twitter.com/rmoff/[contact me on Twitter] and I'll update this blog :) 

I ran several things, and what I *think* fixed it was: 

1. Installed XCode from the app store. It _was_ installed previously, don't know why it wasn't any more (OS upgrade maybe?).
2. Run `sudo xcodebuild -license` and scroll down and type `accept`. I didn't do this step at first and you do need to
3. For each of the `gem` errors, run the suggested `gem pristine` command, with `sudo`: 
+
[source,bash]
----
sudo gem pristine posix-spawn --version 0.3.13
sudo gem pristine ruby-debug-ide --version 0.6.0
…etc
----

4. I also ran a `brew install ruby` - I don't know if this helped or not. 