---
title: 'OBIEE, Big Data Discovery, and ODI security updates - October 2016'
date: "2016-10-19T00:00:00+00:00"
url: "/2016/10/19/obiee-and-odi-security-updates-october-2016/"
draft: false
categories:
- OBIEE
- ODI
- Big Data Discovery
original_source: "rittmanmead"
original_url: "https://www.rittmanmead.com/blog/2016/10/obiee-and-odi-security-updates-october-2016/"
classes:
- feature-nohdr
---

NOTE: This post originally appeared on the link:https://www.rittmanmead.com/blog/2016/10/obiee-and-odi-security-updates-october-2016/[Rittman Mead blog].

Oracle release their "Critical Patch Update" (CPU) notices every quarter, bundling together details of vulnerabilities and associated patches across their entire product line. October's was link:http://www.oracle.com/technetwork/security-advisory/cpuoct2016-2881722.html[released yesterday], with a few entries of note in the analytics & DI space.


Each vulnerability is given a unique identifier (`CVE-xxxx-xxxx`) and a score out of ten. The scoring uses a common link:http://www.first.org/cvss[industry-standard scale] on the basis of how easy it is to exploit, and what is compromised (availability, data, etc). Ten is the worst, and I would crudely paraphrase it as generally meaning that someone can wander in, steal your data, change your data, and take your system offline. Lower than that and it might be that it requires extensive skills to exploit, or the impact be much lower.


A final point to note is that the security patches that are released are not available for old versions of the software. For example, if you're on *OBIEE 11.1.1.6 or earlier*, and it is affected by the vulnerability listed below (which I would assume it is), *there is no security patch*. So even if you don't want to update your version for the latest functionality, staying within support is an important thing to do and plan for. You can see the dates for OBIEE versions and when they go out of "Error Correction Support" link:https://support.oracle.com/epmos/faces/DocContentDisplay?id=1664916.1[here].


If you want more information on how Rittman Mead can help you plan, test, and carry out patching or upgrades, please do get in touch!


_The vulnerabilities listed below are not a comprehensive view of an Oracle-based analytics/DI estate - things like the database itself, along with Web Logic Server, should also be checked. See the link:http://www.oracle.com/technetwork/security-advisory/cpuoct2016-2881722.html[CPU] itself for full details._


== Big Data Discovery (BDD)


* link:http://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2015-3253[CVE-2015-3253]

** Affected versions: 1.1.1, 1.1.3, 1.2.0
** Base score: 9.8
** Action: link:http://docs.oracle.com/cd/E76382_01/bigData.Doc/upgrade_onPrem/toc.htm#About%20this%20guide[upgrade] to the latest version, 1.3.2. _Note that the upgrade packages are on  Oracle Software Delivery Cloud (née eDelivery)_
+
== OBIEE


* link:https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2107[CVE-2016-2107]

** Affected versions: 11.1.1.7.0, 11.1.1.9.0, 12.1.1.0.0, 12.2.1.1.0
** Base score: 5.9
** Action: apply bundle patch 161018 for your particular version (see link:https://support.oracle.com/rs?type=doc&id=2171485.1#chdhbgdd[MoS doc 2171485.1] for details)
+
== BI Publisher


* link:http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2016-3473[CVE-2016-3473]

** Affected versions: 11.1.1.7.0, 11.1.1.9.0, 12.2.1.0.0
** Base score 7.7
** Action: apply patch per link:https://support.oracle.com/rs?type=doc&id=2171485.1#chdhbgdd[MoS doc 2171485.1]
+
== ODI


* link:http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2016-5602[CVE-2016-5602]


** Affected versions: 11.1.1.7.0, 11.1.1.9.0, 12.1.3.0.0, 12.2.1.0.0, 12.2.1.1.0
** Base score: 5.7
** The `getInfo()` ODI API could be used to expose passwords for data server connections.
** More details in link:https://support.oracle.com/CSP/main/article?cmd=show&type=NOT&id=2188855.1[MoS doc 2188855.1]
+
* link:http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2016-5618[CVE-2016-5618]


** Affected versions: 11.1.1.7.0, 11.1.1.9.0, 12.1.2.0.0, 12.1.3.0.0, 12.2.1.0.0, 12.2.1.1.0
** Base score: 3.1
** This vulnerability documents the potential that a developer could take the master repository schema credentials and use them to grant themselves SUPERVISOR access. Even using the secure wallet, the credentials are deobfuscated on the local machine and therefore a malicious developer could still access the credentials in theory.
** More details in link:https://support.oracle.com/CSP/main/article?cmd=show&type=NOT&id=2188871.1[MoS doc 2188871.1]
+
NOTE: This post originally appeared on the link:https://www.rittmanmead.com/blog/2016/10/obiee-and-odi-security-updates-october-2016/[Rittman Mead blog].
